### ISSUE TITLE
Arquitectura básica de la base de datos

### ISSUE THREAD

**Issue by josemmo** [fti-eui-uva-es/bdt#1]
Establecer tablas, columnas y relaciones para la base de datos

**Comment by david-montalvoo** [comment]
Código de la versión 1 de la base de datos.
[bdt.txt](https://github.com/fti-eui-uva-es/bdt/files/925911/bdt.txt)

El código ha sido generado a través del siguiente modelo Entidad/Reacción
![Uploading Modelo base para generar código sql.jpg…]()

**Comment by david-montalvoo** [comment]
Código de la versión 2 de la base de datos.
[base_de_datos_v2.txt](https://github.com/fti-eui-uva-es/bdt/files/936624/base_de_datos_v2.txt)

**Comment by Pablompg** [comment]
Código de la versión 3 de la base de datos. Contempla todos los casos de USO hasta este momento. Las claves foráneas no están creadas, si hicieran falta es solo añadirlas en el sql siguiendo el modelo entidad relación proporcionado por Adrián. El archivo está en txt debido a que GitHub no permite añadir el código en .sql
[banco_del_tiempo.txt](https://github.com/fti-eui-uva-es/bdt/files/983773/banco_del_tiempo.txt)

**Comment by Pablompg** [comment]
Adjunto un zip en el cuál está la base de datos versión 3
[Base de Datos Banco del Tiempo.zip](https://github.com/fti-eui-uva-es/bdt/files/990715/Base.de.Datos.Banco.del.Tiempo.zip)

**Comment by Pablompg** [comment]
Adjunto la Base de Datos versión 4.
[BancoDelTiempoBaseDeDatos.zip](https://github.com/fti-eui-uva-es/bdt/files/1010086/BancoDelTiempoBaseDeDatos.zip)

**Comment by Pablompg** [comment]
Versión FINAL FINAL FINAL de la base de Datos 
[BancoDelTiempo.zip](https://github.com/fti-eui-uva-es/bdt/files/1019180/BancoDelTiempo.zip)
